name: dynamic_gaussians
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - python=3.8.18
  - pip=24.3.1
  - pytorch=2.1.2
  - torchaudio=2.1.2
  - torchvision=0.16.2
  - pytorch-cuda=11.8
  - tqdm=4.66.6
  - Pillow=10.4.0
  - pip:
    - open3d==0.17.0
